apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "magi.fullname" . }}-backend-config
  labels:
    {{- include "magi.labels" . | nindent 4 }}
data:
  MAGI_HTTP_ADDR: ":8080"
  MAGI_DB_DRIVER: {{ .Values.configuration.dbDriver | quote }}
  MAGI_MODEL_BASE_URL: {{ .Values.configuration.modelBaseURL | quote }}
  MAGI_MODEL_NAME: {{ .Values.configuration.modelName | quote }}
  MAGI_EMBEDDING_BASE_URL: {{ .Values.configuration.embeddingBaseURL | quote }}
  MAGI_EMBEDDING_MODEL_NAME: {{ .Values.configuration.embeddingModelName | quote }}
  MAGI_MILVUS_ADDRESS: {{ .Values.configuration.milvusAddress | quote }}
  MAGI_ES_ADDRESSES: {{ .Values.configuration.esAddresses | quote }}
  MAGI_AUTH_ENABLED: {{ .Values.configuration.authEnabled | quote }}
