{{- if .Values.backend.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "magi.fullname" . }}-backend
  labels:
    {{- include "magi.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.backend.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "magi.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
{{- end -}}
