{{- if .Values.common.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "magi.serviceAccountName" . }}
  labels:
    {{- include "magi.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.common.serviceAccount.automountServiceAccountToken }}
{{- end -}}
